version: '3.8'

services:
  contenedor-mysql:
    image: mysql:8.0
    container_name: mysql_dualtarot
    restart: always
    environment:
      MYSQL_DATABASE: tarot_db
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app-web:
    build: .
    container_name: java_dualtarot
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - contenedor-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://contenedor-mysql:3306/tarot_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

volumes:
  db_data: